### ISSUE TITLE
Dogs & Flak Troopers don't get a speed boost as they do in Vanilla RA2

### ISSUE THREAD

**Issue by MJvst** [CnCNet/yr-patches#15]
In Vanilla RA2:
- When dogs & Flak troppers are stationary, attacked, then commanded to move, they start running (crawling for Flak Tropper) and get a speed boost as shown in these videos for [dogs](https://cdn.discordapp.com/attachments/402908559815213056/1073322022601511002/2023-02-09_21-17-30.mp4) and [flak troopers](https://cdn.discordapp.com/attachments/402908559815213056/1073326012852600992/2023-02-09_21-33-49.mp4) 
- Note: in the dog video, pay attention to the 2nd dog, not the first dog.

In CnCNet RA2:
- When dogs & flak troopers are stationary, attacked, then commanded to move, they start running and **do not** get a speed boost

Request:
- To make the dogs in CnCNet RA2 closer to vanilla RA2

Reason:
- the speed boost gives tank battles with fodder more randomness and less predictability 
- currently, dog behaviour is very predictable due to the absence of the speed boost
- with the speed boost, dogs will be able to run past tanks, causing the tanks to turn their turret (main use of fodder) or reach other dogs quicker
- this speed boost also allows dogs to eat infantry a lot quicker (which helps allies as sovs are overpowered)

**Comment by Starkku** [comment]
I did some investigating because I was curious as to what would make this happen. I can't tell exactly how this works in RA2, but in YR there is a (presumably leftover) bit of code that adds 50% extra to infantry movement speed if the infantry is currently 'prone' or 'crawling' but the InfantryType has `Crawls=false` in `artmd.ini`. This does not normally come into play because infantry cannot enter prone stage if `Crawls` is not set due to a check at `0x51D77A`, which I suspect was introduced in YR. The whole thing is probably a bug though, but I guess to reproduce RA2 gameplay could consider reimplementing it.
